version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    env_file:
      - .env
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    ports:
      - 3306:3306
  nginx:
    hostname: yeti
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: nginx 
    volumes:
      - type: volume
        source: crm_data
        target: /var/www/html
    ports:
      - 80:80
  cron:
    build:
      context: ./cron
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
    volumes_from:
      - nginx:ro
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: php-prod
    volumes_from:
      - nginx:rw
volumes:
  crm_data:
  db_data: