name: yetiforce-test
version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    env_file:
      - .env
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: php-test
    depends_on:
      - db